apiVersion: apps/v1
kind: Deployment
metadata:
    name: example
    labels:
      app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: local/example:latest
        name: example
        imagePullPolicy: Never
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
    name: example
spec:
    type: NodePort
    selector:
        app: example
    ports:
        - port: 8080
          targetPort: 8080
