apiVersion: apps/v1
kind: Deployment
metadata:
    name: example
    labels:
      app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: penyo/devops-u11:${{ github.sha }}
        name: example
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: my-secret


---
apiVersion: v1
kind: Service
metadata:
    name: example
spec:
    type: ClusterIP
    selector:
        app: example
    ports:
        - port: 8080
          targetPort: 8080
